# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us.xci
# IP: The module: 'fifo_us' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_us'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_us'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us.xci
# IP: The module: 'fifo_us' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_us'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/halaldeen-ms/Dev/gaussian_filter/gaussian_filter.srcs/sources_1/ip/fifo_us/fifo_us_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_us'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
